version: "3.7"

services:
  web:
    build:
      context: "."
      args:
        UID: "$UID"
        GID: "$GID"
    ports:
      - "${EXPOSE_APP_PORT:-9000}:9000"
    depends_on:
      - "db"

  db:
    image: "mysql:8.0"
    ports:
      - "${EXPOSE_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "db:/var/lib/mysql"
      - "./docker/db:/etc/mysql/conf.d"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

volumes:
  db:
    driver: local
